### ISSUE TITLE
Don't can use to plot a graph.

### ISSUE THREAD

**Issue by tixel1** [tkeffer/weewx-xaggs#2]
I can't use to plot a graph.
In the skin.conf i write 
[[[historical]]]
  [[[[outtemp]]]]
     aggregate_type = historical_min
But nothing ocurs.
If I add aggregate_interval = day an error ocurs
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****  outTemp.historical_min
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****      obj.start()
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****      self.run()
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 41, in run
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 181, in genImages
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****      aggregate_interval=aggregate_interval)
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 99, in get_series
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****      raise weewx.UnknownType(obs_type)
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****  weewx.UnknownType: outTemp.historical_min
Dec  9 16:10:24 raspberrypi weewx[22716] ERROR weewx.reportengine:         ****  Generator terminated

**Comment by tkeffer** [comment]
Works for me.

I used the following:

```ini
    [[month_images]]
        x_label_format = %d
        bottom_label_format = %x %X
        time_length = 2592000    # == 30 days
        aggregate_type = avg
        aggregate_interval = 10800    # == 3 hours
        show_daynight = false
        

        [[[monthtemp]]]
            [[[[outTemp]]]]
            [[[[historical_lo]]]]
                aggregate_type = historical_min
                aggregate_interval = day
                data_type = outTemp
                label = historical low
            [[[[historical_high]]]]
                aggregate_type = historical_max
                aggregate_interval = day
                data_type = outTemp
                label = historical high
```

This results in this plot:
![image](https://user-images.githubusercontent.com/3321259/184042788-40304227-9db5-4c5a-ac29-46f81fdc841e.png)
